sudo: required
  
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  
notifications:
  email:
    on_success: never
    on_failure: never

install:
  - npm install

script:
  - npm run ci
  
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info